blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blogs import urls as blogs_url
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mce/', include('tinymce.urls')),
    path('', include(blogs_url), name='blogs'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path
from .views import home, post, search


app_name = 'blogs'

urlpatterns = [
    path('', home, name='home'),
    path('post/<int:id>', post, name='post'),
    path('search/', search, name='search'),
]

blogs/models.py
from django.db import models
from tinymce import models as mce_model


# Create your models here.


class post(models.Model):

    AUTHORS = [
        ('npoudelp', 'npoudelp'),
        ('bqtbsb', 'bqtbsb'),
    ]

    STAT = [
        ('draft', 'draft'),
        ('publish', 'publish'),
    ]

    thumbnail = models.ImageField(blank=True, null=True)
    author = models.CharField(choices=AUTHORS, max_length=25)
    title = models.CharField(max_length=255)
    blog = mce_model.HTMLField(null=True, blank=True)
    date = models.DateField()   
    tags = models.CharField(max_length=25, default='Empty')
    description = models.TextField(null=True, blank=True)
    status = models.CharField(choices=STAT, max_length=25, default='draft')

    def __str__(self):
        return f'{self.title} -> {self.status}'

blogs/views.py
from django.shortcuts import render
from .models import post as posts

# Create your views here.


def home(request):
    blogs = posts.objects.filter(status='publish').order_by('-id')
    res = {
        'blogs':blogs,
    }
    return render(request, 'home.html', res)


def post(request, id):
    one_post = posts.objects.get(id=id)
    res = {
        'blog':one_post,
    }
    return render(request, 'post.html', res)


def search(request):
    key = request.POST.get('key')
    blogs = posts.objects.filter(title__contains=key) | posts.objects.filter(blog__contains=key)

    res = {
        'blogs':blogs,
    }
    return render(request, 'home.html', res)

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <title>{% block title %}{% endblock %}</title>

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300&family=Rubik+Maps&display=swap');

        .aspBlog {
            font-family: 'Poppins', sans-serif;
            font-family: 'Rubik Maps', system-ui;
        }

        .title {
            font-weight: 600;
        }

        .be_round {
            border-radius: 30px;
        }
    </style>

</head>

<body class="bg-dark text-light">

    <div class="container">
        <div class="row mb-5">
            <div class="col-md-6">
                <p class="text-lg-right text-center display-3 aspBlog">
                    aspBlog
                </p>
            </div>
            <div class="col-md-6 align-middle">
                <form class="form-inline pt-lg-4 pt-md-4 pt-sm-0" method="POST" action="{% url 'blogs:search' %}">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="key" placeholder="Search for blog...">
                        <div class="input-group-append">
                            <input type="submit" value="Search" class="input-group-text text-dark" id="basic-addon2">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        {% block body %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}aspBlog{% endblock %}

{% block body %}
{% for blog in blogs %}

<div class="row py-4">
    <div class="col-md-4">
        <img src="{{blog.thumbnail.url}}" class="img-fluid be_round" alt="Responsive image">
    </div>
    <div class="col-md-8">
        <p class="text-muted">
            by <span class="font-weight-bold text-white mr-5">{{blog.author}}</span>
            <span class="">
                <i class="bi bi-calendar-week"></i> {{blog.date}}
            </span>
        </p>
        <p class="h3 title">
            {{blog.title|safe}}
        </p>
        <p class="text-truncate">
            {{ blog.description|safe }}
        </p>
        <a href="{% url 'blogs:post' id=blog.id %}">
            <span class="btn-outline-light btn be_round">Read More</span>
        </a>
    </div>
</div>

{% endfor %}

{% endblock %}

templates/post.html
{% extends 'base.html' %}

{% block title %}aspBlog{% endblock %}

{% block body %}
    <div class="container">
        <img src="{{blog.thumbnail.url}}" style="height: 45vh; width: 100vw;" class="img-fluid be_round" alt="image">
    </div>
    <div class="container">
        <p class="text-muted">
            by <span class="font-weight-bold text-white mr-5">{{blog.author}}</span>
            <span class="">
                <i class="bi bi-calendar-week"></i> {{blog.date}}
            </span>
        </p>
        <p class="h3 title">
            {{blog.title|safe}}
        </p>
        <p class="text-truncate">
            {{ blog.blog|safe }}
        </p>
        <a href="{% url 'blogs:post' id=blog.id %}">
            <span class="btn-outline-light btn be_round">Read More</span>
        </a>
    </div>

    <div class="container p-5">
        <p class="text-center text-muted">
            
        </p>
    </div>

{% endblock %}